### ISSUE TITLE
Enhancement: UTXO Selection for Transaction Optimization

### ISSUE THREAD

**Issue by yilakb** [inscrib3/inspip#17]
Request:
Pipe wallet to enhance its UTXO selection process during transactions. Currently, the wallet's approach leads to the creation of unnecessary 'change' UTXOs even when they are not required.

Description:
The Pipe wallet currently faces a unique challenge since all UTXOs are uniform at 546 sats, making it challenging to prioritize based on just utxo. Therefore, I propose the implementation of a mechanism that enables the Pipe wallet to intelligently calculate which UTXOs to use based on the token amount.

Benefits:

Lower Transaction Fees: Prioritizing token closer in value to the transaction amount will reduce the number of UTXOs involved, leading to lower transaction fees for users.

Optimized UTXO Management: This feature would optimize UTXO management by avoiding unnecessary 'change' UTXOs, resulting in a cleaner and more efficient UTXO structure.

Improved User Experience: Users will benefit from a more seamless and cost-effective transaction process, ultimately enhancing their experience with the Pipe wallet.

Implementation Considerations:
The mechanism could involve evaluating number of token in the given UTXOs and selecting those that are closest in value to the transaction amount. This would require adjustments to the wallet's logic for token selection .

**Comment by thewrlck** [comment]
Thank you for your precious feedback this issue should be fixed. Feel free to reopen if needed
