### ISSUE TITLE
Can not show balance correctly if import WIF from other wallet

### ISSUE THREAD

**Issue by ziggy-hung** [inscrib3/inspip#22]
Hi,Dev,I just tred to import WIF from a address with some btc balance which was generated by UNISAT wallet(google extention) ,the address starts with bc1p,I believe it is taproot address,after import inspip(google extention) can show the address correctly but all balance is zero.then someone sent me some pipe,I can check the pipe balance I received on ppline.app and satx.io but inspip can not show these pipe
trid on different computers,both WIN(Windows 10) and OSX(intel based Catalina),all have the same problem
does this mean I have to use address generated by inspip itself to use pipe protocol?thanks!

**Comment by thewrlck** [comment]
I closed this issue because the problems should not persist on the latest version
